version: "3.9"

services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "5001:5001"
    env_file:
      - ./auth_service/.env

  favorite_service:
    build: ./favorite_service
    container_name: favorite_service
    ports:
      - "5002:5002"
    env_file:
      - ./favorite_service/.env
    depends_on:
      - auth_service

  ai_service:
    build: ./ai_service_python
    container_name: ai_service
    ports:
      - "5003:5003"
    env_file:
      - ./ai_service_python/.env
    depends_on:
      - auth_service
